backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: 'reviews'
    label: 'Reviews'
    folder: 'cms/reviews'
    create: true
    slug: '{{slug}}'
    fields:
      - { name: 'title', label: 'Review Title', widget: 'string' }
      - { name: 'description', label: 'Description', widget: 'text' }
      - { name: 'rating', label: 'Rating (1-5)', widget: 'number', min: 1, max: 5 }
      - { name: 'body', label: 'Review Content', widget: 'markdown' }
      
  # Corrected Home Page configuration
  - name: 'site-content'
    label: 'Site Content'
    files:
      - name: "home-page"
        label: "Home Page"
        file: "cms/home-data.md"
        format: "frontmatter"
        fields:
          - { label: "Featured Categories", name: "featuredCategories", widget: "list", required: false, allow_add: true, hint: "A list of category slugs to feature on the homepage." }
          - { label: "Featured Posts", name: "featuredPosts", widget: "list", required: false, allow_add: true, fields: [ { label: "Category", name: "category", widget: "string" }, { label: "Post", name: "post", widget: "string" } ] }
          - { label: "Featured Jobs", name: "featuredJobs", widget: "list", required: false, allow_add: true, fields: [ { label: "Category", name: "category", widget: "string" }, { label: "Job", name: "job", widget: "string" } ] }

      # Corrected Categories configuration
      - name: "categories"
        label: "Categories"
        file: "cms/categories.json"
        fields:
          - {
              label: "Categories",
              name: "categories",
              widget: "list",
              summary: "{{fields.title}}",
              fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Slug", name: "slug", widget: "string"},
                {label: "Icon", name: "icon", widget: "image", required: false, media_folder: "public/icons", public_folder: "/icons"},
                {label: "Cover Image", name: "coverImage", widget: "image", required: false, media_folder: "public/images/categories", public_folder: "/images/categories"},
                {label: "Description", name: "description", widget: "string"},
                {label: "Category Introduction", name: "introduction", widget: "markdown", required: false},
                {label: "Featured on Homepage", name: "featured", widget: "boolean", default: false},
                {label: "Navigation Group", name: "navGroup", widget: "select", options: ["main", "dropdown"], default: "main"},
                {label: "SEO Title", name: "seoTitle", widget: "string", required: false},
                {label: "SEO Description", name: "seoDescription", widget: "text", required: false},
                {label: "Keywords", name: "keywords", widget: "list", required: false},
                {label: "Sort By", name: "sortBy", widget: "select", options: ["date", "title", "level", "deadline"], default: "date"},
                {label: "Sort Order", name: "sortOrder", widget: "select", options: ["asc", "desc"], default: "desc"},
                {label: "Canonical URL", name: "canonicalUrl", widget: "string", required: false},
                {label: "Featured Posts", name: "featuredPosts", widget: "list", fields: [
                  {label: "Post Slug", name: "slug", widget: "string"}
                ]}
              ]
            }

      # Corrected Stats configuration
      - name: "stats"
        label: "Stats"
        file: "cms/stats.json"
        fields:
          - {
              label: "Stats",
              name: "stats",
              widget: "list",
              summary: "{{fields.title}}",
              fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Value", name: "value", widget: "string"},
                {label: "Icon", name: "icon", widget: "string"}
              ]
            }
  
  # All your other folder-based collections remain the same below
  - name: "blog-posts"
    label: "Blog Posts"
    folder: "content/blog-posts"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Reading Time", name: "reading_time", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "career-advancement"
    label: "Career Advancement"
    folder: "content/career-advancement"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "scholarships"
    label: "Scholarships"
    folder: "content/scholarships"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Deadline", name: "deadline", widget: "datetime"}
      - {label: "Eligibility", name: "eligibility", widget: "markdown"}
      - {label: "Amount", name: "amount", widget: "string"}
      - {label: "Application Link", name: "application_link", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false, media_folder: "public/images/categories", public_folder: "/images/categories"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "coding-courses"
    label: "Coding Courses"
    folder: "content/coding-courses"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"]}
      - {label: "Duration", name: "duration", widget: "string"}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Skills", name: "skills", widget: "list"}
      - {label: "Course Image", name: "course_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "personal-development"
    label: "Personal Development"
    folder: "content/personal-development"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "job-board"
    label: "Job Board"
    folder: "content/job-board"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Job Title", name: "title", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Job Type", name: "job_type", widget: "select", options: ["Full-time", "Part-time", "Contract", "Internship"]}
      - {label: "Salary Range", name: "salary_range", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Requirements", name: "requirements", widget: "markdown"}
      - {label: "Application Link", name: "application_link", widget: "string"}
      - {label: "Posted Date", name: "date", widget: "datetime"}

  - name: "health-wellness"
    label: "Health & Wellness"
    folder: "content/health-wellness"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "creative-skills"
    label: "Creative Skills"
    folder: "content/creative-skills"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "digital-skills"
    label: "Digital Skills"
    folder: "content/digital-skills"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "education"
    label: "Education"
    folder: "content/education"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "entrepreneurship"
    label: "Entrepreneurship"
    folder: "content/entrepreneurship"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "financial-aid"
    label: "Financial Aid"
    folder: "content/financial-aid"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "learning-resources"
    label: "Learning Resources"
    folder: "content/learning-resources"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "lifestyle"
    label: "Lifestyle"
    folder: "content/lifestyle"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"], required: false}
      - {label: "Duration", name: "duration", widget: "string", required: false}
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
