backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "categories"
    label: "Categories"
    folder: "cms"
    file: "cms/categories.json"
    fields:
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          summary: "{{fields.title}}",
          fields: [
            {label: "Title", name: "title", widget: "string"},
            {label: "Slug", name: "slug", widget: "string"},
            {label: "Icon", name: "icon", widget: "image", required: false, media_folder: "public/icons", public_folder: "/icons"},
            {label: "Description", name: "description", widget: "string"},
            {label: "Featured on Homepage", name: "featured", widget: "boolean", default: false},
            {label: "Category Introduction", name: "introduction", widget: "markdown", required: false}
          ]
        }
  
  - name: "home-page"
    label: "Home Page"
    file: "cms/home.json"
    fields:
      - {label: "Hero Title", name: "hero_title", widget: "string"}
      - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string", required: false}
      - label: "Stats"
        name: "stats"
        widget: "list"
        fields:
          - {label: "Value", name: "value", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Icon", name: "icon", widget: "string"}
      - label: "Trending Posts"
        name: "trending_posts"
        widget: "list"
        fields:
          - {label: "Post Title", name: "title", widget: "string"}
          - {label: "Post Slug", name: "slug", widget: "string", hint: "The slug of the post (e.g., how-to-apply-for-educational-grants)"}
          - {label: "Post Excerpt", name: "excerpt", widget: "string", required: false}
          - {label: "Featured Image", name: "image", widget: "image", required: false}
      - label: "Featured Jobs"
        name: "featured_jobs"
        widget: "list"
        fields:
          - {label: "Job ID", name: "id", widget: "string"}
          - {label: "Job Title", name: "title", widget: "string"}
          - {label: "Company", name: "company", widget: "string"}
          - {label: "Company Logo", name: "companyLogo", widget: "image", required: false}
          - {label: "Location", name: "location", widget: "string"}
          - {label: "Tags", name: "tags", widget: "list", required: false}
          - {label: "Application Link", name: "link", widget: "string", required: false}

  - name: "blog-posts"
    label: "Blog Posts"
    folder: "content/blog-posts"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Education", "Technology", "Career", "Personal Development"]}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "career-advancement"
    label: "Career Advancement"
    folder: "content/career-advancement"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}

  - name: "scholarships"
    label: "Scholarships"
    folder: "content/scholarships"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Amount", name: "amount", widget: "string"}
      - {label: "Deadline", name: "deadline", widget: "datetime"}
      - {label: "Eligibility", name: "eligibility", widget: "text"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Application Link", name: "application_link", widget: "string", required: false}

  - name: "coding-courses"
    label: "Coding Courses"
    folder: "content/coding-courses"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Level", name: "level", widget: "select", options: ["Beginner", "Intermediate", "Advanced"]}
      - {label: "Duration", name: "duration", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Skills", name: "skills", widget: "list"}
      - {label: "Course Image", name: "course_image", widget: "image", required: false}

  - name: "personal-development"
    label: "Personal Development"
    folder: "content/personal-development"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}

  - name: "job-board"
    label: "Job Board"
    folder: "content/job-board"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Job Title", name: "title", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Job Type", name: "job_type", widget: "select", options: ["Full-time", "Part-time", "Contract", "Internship"]}
      - {label: "Salary Range", name: "salary_range", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Requirements", name: "requirements", widget: "markdown"}
      - {label: "Application Link", name: "application_link", widget: "string"}
      - {label: "Posted Date", name: "date", widget: "datetime"}

  - name: "health-wellness"
    label: "Health & Wellness"
    folder: "content/health-wellness"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}

  - name: "creative-skills"
    label: "Creative Skills"
    folder: "content/creative-skills"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}

  - name: "digital-skills"
    label: "Digital Skills"
    folder: "content/digital-skills"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}

  - name: "education"
    label: "Education"
    folder: "content/education"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}

  - name: "entrepreneurship"
    label: "Entrepreneurship"
    folder: "content/entrepreneurship"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}

  - name: "financial-aid"
    label: "Financial Aid"
    folder: "content/financial-aid"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}

  - name: "learning-resources"
    label: "Learning Resources"
    folder: "content/learning-resources"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}

  - name: "lifestyle"
    label: "Lifestyle"
    folder: "content/lifestyle"
    create: true
    slug: "{{year}}/{{month}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
